### ISSUE TITLE
Processes killed and semaphore objects leaked when reading pandas data

### ISSUE THREAD

**Issue by Alalalalaki** [arrow-py/arrow#1000]
## Issue Description

When I run `pa.Table.from_pandas(df)` for a >1G dataframe, it reports 

```
Killed: 9
anaconda3/envs/py38/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
```

## System Info

- 🖥  **OS name and version**:  macOS 11.4
- 🐍  **Python version**: 3.8.10
- 🏹  **Arrow version**: 4.0.1

**Comment by jadchaar** [comment]
Hi @Alalalalaki, I don’t think this is related to arrow but is instead a Pandas issue. What made you think it was an arrow issue :)?

**Comment by Alalalalaki** [comment]
@jadchaar Thanks for your reply. I am not sure what issue this error belongs to. I think I might load more data than my RAM capacity. Is there a way in arrow to avoid this issue?
