### ISSUE TITLE
No documentation of format of get() and format()

### ISSUE THREAD

**Issue by alexchandel** [arrow-py/arrow#1005]
## Issue Description

There is no documentation of all the allowed format characters for `arrow.get()` and `Arrow.format()`.  The documentation mentions a few examples, like `arrow.get('June was born in May 1980', 'MMMM YYYY')` and `arrow.utcnow().format('YYYY-MM-DD HH:mm:ss ZZ')`, but these are far from exhaustive.

For example, how does one output a human-readable weekday name, like "Thursday, July 4"?   Even python's `datetime` has `datetime.datetime.now().strftime('%A')` and `datetime.date.today().strftime('%A')`.  Surely arrow can at least do this in its `format()`?

The source of [parser.py](https://github.com/arrow-py/arrow/blob/master/arrow/parser.py) and [formatter.py](https://github.com/arrow-py/arrow/blob/master/arrow/formatter.py) show quite a few format characters that aren't exhibited in the documentation.  Please document the meaning of/difference between all these.

**Comment by jadchaar** [comment]
Hi @alexchandel, the token documentation can be found [here](https://arrow.readthedocs.io/en/latest/#supported-tokens).
