### ISSUE TITLE
Arrow 1.1.1 doesn't support get from decimal, but 0.15.2 support

### ISSUE THREAD

**Issue by mousehappy** [arrow-py/arrow#1033]
## Issue Description

Arrow 1.1.1 doesn't support get from decimal, but 0.15.2 support

![image](https://user-images.githubusercontent.com/5227779/132082537-95bb3257-ab3f-4391-8717-05fea44142ca.png)

OS: Darwin Kernel Version 20.3.0
OS: Centos7
## System Info

- 🖥  **OS name and version**: 
- 🐍  **Python version**: 
- 🏹  **Arrow version**:

**Comment by krisfremen** [comment]
@mousehappy Thanks for reporting this in!

I can replicate, 0.16.0 and above fail on parsing a decimal.

**Comment by krisfremen** [comment]
@mousehappy hey, this just got fixed in the latest master commit.

Thanks again for taking the time to report this in!
