### ISSUE TITLE
handling of leading spaces in month, day, and hours by parser

### ISSUE THREAD

**Issue by rtphokie** [arrow-py/arrow#1066]
## Issue Description

Currently arrow can parse 1 or two digit day of the month with or without a leading zero.  It does not handle a leading space however.  A leading space before a single digit day of the month, month number, or hour is formatting found commonly (lines up better, offers some sorting benefits, etc.) and should be handled better.

Workaround: replace double spaces with a single space before passing to arrow.get()

e.g. 

datestring = 'Jan  1 2022'
dt = arrow.get(datstring.replace('. ', ' '). 'MMM D YYYY')

## System Info

- 🖥  **OS name and version**:  MacOS 11.6.1
- 🐍  **Python version**: Python 3.9.1
- 🏹  **Arrow version**:  1.2.1

**Comment by systemcatch** [comment]
Hello @rtphokie, your example seems to work fine for me without replacement.

```shell
>>> datestring = 'Jan 9 2022'
>>> arrow.get(datestring, 'MMM D YYYY')
<Arrow [2022-01-09T00:00:00+00:00]>
```

For situations with extra whitespace use the `normalize_whitespace` flag.
```shell
>>> datestring_spaced = 'Jan  9 2022'
>>> arrow.get(datestring_spaced, 'MMM D YYYY', normalize_whitespace=True)
<Arrow [2022-01-09T00:00:00+00:00]>
```
https://arrow.readthedocs.io/en/latest/#redundant-whitespace

**Comment by rtphokie** [comment]
Missed that flag, thanks for pointing it out.

Shouldn't that be default behavior though?

**Comment by systemcatch** [comment]
We don't like to assume what the user wants, or do too much hidden processing of the string. Easier for them to explicitly invoke the flag.
