### ISSUE TITLE
Be consistent with the pluralisation of units

### ISSUE THREAD

**Issue by Kaju-Bubanja** [arrow-py/arrow#1115]
## Feature Request

In version 1.2.2 the function `replace` takes the units without the ending s and the `shift` function takes it with the s.

```
# exception
arrow.now().shift(second=3)
# works
arrow.now().shift(seconds=3)
# works
arrow.now().replace(second=3)
# exception
arrow.now().replace(seconds=3)
```

**Comment by systemcatch** [comment]
Hi @Kaju-Bubanja this is partly due to the old versions of arrow combining `replace` and `shift`. At this point I don't think this is worth altering.

**Comment by Kaju-Bubanja** [comment]
So is the idea to completely replace one of the functions?

**Comment by systemcatch** [comment]
replace and shift used to be one function which had different actions based on use of plurals. This made errors based on input very likely, so the function was split into replace and shift.

We are not planning to make any changes to these.
