### ISSUE TITLE
User Documentation Difficult to Read Because of Index

### ISSUE THREAD

**Issue by scottfurry** [arrow-py/arrow#1128]
## Issue Description
User Documentation Difficult to Read Because of Index

The indentation of numerous languages under `arrow.locale` causes the document index to overlap the user examples. This makes reading and comprehending the arrow library difficult to understand. Screenshot of situation attached.

![Py_Arrow_ReadDocs](https://user-images.githubusercontent.com/6686571/194394689-49615a21-d101-4c9f-ac25-8d032e611205.jpg)

**Comment by lmmentel** [comment]
This would be great to be fixed since the documentation right now is not very usable.

![image](https://user-images.githubusercontent.com/8989838/196013629-a8093c7d-c0fd-4326-add1-3f914a1eda96.png)

**Comment by krisfremen** [comment]
I will review and merge the PR for this later today.

**Comment by krisfremen** [comment]
Resolved with #1134 and #1135.
