### ISSUE TITLE
Fuzzing arrow on OSS-Fuzz

### ISSUE THREAD

**Issue by rikfie** [arrow-py/arrow#1147]
Hi there, 

Are you interested to get arrow fuzzed*? I have written a [harness for arrow](https://github.com/rikfie/arrow-py-fuzzer) and it's ready to be integrated. Many libraries are being fuzzed on [OSS-Fuzz](https://github.com/google/oss-fuzz) on a daily basis and I would like to add arrow. 

The only condition for fuzzing on OSS-Fuzz is that any bugs found must be fixed and released within 90 days; the bug will be publicly disclosed past this point.

If you're interested, please provide me with an e-mail address of a maintainer. The e-mail address must be linked to a Google account. Note that the addresses will be stored in a public repository. If this is not an option, I can forward bug reports to you. Although I can propose for the integration of arrow to OSS-Fuzz, the decision is up to OSS-Fuzz.

\* Fuzz testing is a well-known technique for uncovering programming errors in software. OSS-Fuzz aims to make common open source software more secure and stable by combining modern fuzzing techniques with scalable, distributed execution.

**Comment by krisfremen** [comment]
Closing as done with https://github.com/google/oss-fuzz/pull/10100
