### ISSUE TITLE
Arrow.humanize() thinks past date is in the future

### ISSUE THREAD

**Issue by hermanoelmhagen** [arrow-py/arrow#1148]
## Issue Description

Arrow returns "in xx minutes" for time in the past:
```
>>> arrow.get("16/01/2023, 07:59:48", "DD/MM/YYYY, HH:mm:ss").humanize()
'in 27 minutes'
>>> now = arrow.now()
>>> now
<Arrow [2023-01-16T08:32:25.112674+01:00]>
```
This might be related to humanize() not taking local timezone into account.
Possible workaround is to shift(hours=timezone_diff) before humanizing:
`arrow.get("16/01/2023, 07:59:48","DD/MM/YYYY, HH:mm:ss".shift(hours=-1).humanize()`

## System Info

- 🖥  **OS name and version**: Windows 10 21H2 (19044.2364)
- 🐍  **Python version**: Python 3.11.1
- 🏹  **Arrow version**: 1.2.3

**Comment by krisfremen** [comment]
.get defaults to using UTC unless a time zone is specified, while .now does use the local time zone and .utcnow uses UTC.

Working as intended.

**Comment by krisfremen** [comment]
> .get defaults to using UTC unless a time zone is specified, while .now does use the local time zone and .utcnow uses UTC.

Few examples to illustrate the above:

```
arrow.get(arrow.now().format("DD/MM/YYYY, HH:mm:ss"), "DD/MM/YYYY, HH:mm:ss").humanize()
```
for me this yields the following, but it should be the timezone difference you are in, which in europe you'll be technically "in the future" compared to UTC
> 4 hours ago

UTC time on the other hand
```
arrow.get(arrow.utcnow().format( "DD/MM/YYYY, HH:mm:ss"), "DD/MM/YYYY, HH:mm:ss").humanize()
```
yields
> just now

----
Adding tzinfo when using `arrow.now` you can specify the timezone you want to use.
```
arrow.get(arrow.now().format("DD/MM/YYYY, HH:mm:ss"), "DD/MM/YYYY, HH:mm:ss", tzinfo="America/Montreal").humanize()
```
changing the tzinfo to the timezone you're in should yield:
> just now
