### ISSUE TITLE
'arrow' has no attribute 'utcnow'

### ISSUE THREAD

**Issue by eukiseioh** [arrow-py/arrow#1154]
i installed arrow module in deferents python versions and followed the examples from docs but always it is showing me the same error with the next code:
```
import arrow
utc = arrow.utcnow()
print(utc)
```

error:
utc = arrow.utcnow()
AttributeError: partially initialized module 'arrow' has no attribute 'utcnow' (most likely due to a circular import)

## System Info

- 🖥  **OS name and version**: macOS 11.7.10 
- 🐍  **Python version**: Python 3.10
- 🏹  **Arrow version**: 1.2.3

**Comment by krisfremen** [comment]
@eukiseioh Unfortunately, I can't reproduce the same behavior, and it would be almost impossible without having the same environment.

As such, this is not a bug with arrow itself.
