### ISSUE TITLE
No docs on values in format string for Arrow.format()

### ISSUE THREAD

**Issue by metaperl** [arrow-py/arrow#1167]
The [user guide docs on format](https://arrow.readthedocs.io/en/latest/guide.html#format) do not document the various arguments that can be provided. The [API guide](https://arrow.readthedocs.io/en/latest/api-guide.html#arrow.arrow.Arrow.format) also lacks such information.

**Comment by jadchaar** [comment]
Hi @metaperl we have documentation here: https://arrow.readthedocs.io/en/latest/guide.html#supported-tokens. That said, this can likely be made more obvious. PRs are welcome if you'd like to take this improvement on!
