### ISSUE TITLE
Don't force requirement on types-python-dateutil 

### ISSUE THREAD

**Issue by mredaelli** [arrow-py/arrow#1169]
## Feature Request

A project I work on follows the usual pattern of having two `requirements` file, one for production environments and one for development, compiled by `pip-tools`.

I just noticed that `arrow` adds the `types-python-dateutil` package to my prod `requirements.txt`.

Since typing information should not be necessary at runtime, I think the installation of that package should be left to the user who wants it.

**Comment by bnavigator** [comment]
As a contributor to the maintenance of the openSUSE Tumbleweed Linux Python Stack, I wholeheartedly agree.

https://build.opensuse.org/request/show/1138314

**Comment by sanderr** [comment]
I also feel like this should be a development package. Perhaps it can be exposed as an optional extra `arrow[dev]` or `arrow[types]`? This way you can still make abstraction of your typing requirements for library users, while keeping it contained to those that specifically request it.

**Comment by Lit37** [comment]
> ## Feature Request
> A project I work on follows the usual pattern of having two `requirements` file, one for production environments and one for development, compiled by `pip-tools`.
> 
> I just noticed that `arrow` adds the `types-python-dateutil` package to my prod `requirements.txt`.
> 
> Since typing information should not be necessary at runtime, I think the installation of that package should be left to the user who wants it.



> I also feel like this should be a development package. Perhaps it can be exposed as an optional extra `arrow[dev]` or `arrow[types]`? This way you can still make abstraction of your typing requirements for library users, while keeping it contained to those that specifically request it.

**Comment by jadchaar** [comment]
Fixed by https://github.com/arrow-py/arrow/pull/1183

**Comment by epenet** [comment]
Is there a release planned for this?
