### ISSUE TITLE
Specify start date in span('week')

### ISSUE THREAD

**Issue by mehtadev17** [arrow-py/arrow#355]
arrow.utcnow().span('week') starts on Monday and ends on Sunday. I would like an option to start the week on Sunday and end on Saturday.

**Comment by byin0317** [comment]
I am interested in working on this issue, will look further into by next week or so

**Comment by systemcatch** [comment]
We could use https://docs.python.org/3.8/library/calendar.html#calendar.Calendar for this.

**Comment by sawhitt** [comment]
I am interested in working on this, can I look into it?

**Comment by oakt** [comment]
Can we work on this?

**Comment by jadchaar** [comment]
Hey @oakt, if you’d like to contribute this change, PRs are welcome :).

**Comment by yiransii** [comment]
@jadchaar 
Can I take this?
