### ISSUE TITLE
Add support for reversed humanize

### ISSUE THREAD

**Issue by paulschmeida** [arrow-py/arrow#360]
I think it would be nice if there was a reversed version of humanize, i.e. a function that parses human readable input like "20 hours ago" and produces an Arrow object than can be used in scripts with ease.

**Comment by ju2pom** [comment]
Exactly what I need !

**Comment by andrewelkins** [comment]
#361 would address this I think

**Comment by systemcatch** [comment]
Despite the linked PR now being closed, this is still something we'd like to implement. I think we could do with a good idea for structure + spec before we PR this again though.

**Comment by abschmidt6** [comment]
I'm interested in working on this feature, I will take a look at it!

**Comment by jadchaar** [comment]
Fantastic. Let us know if you have any questions.

**Comment by sawhitt** [comment]
I am interested in working on this, would that be alright?

**Comment by jadchaar** [comment]
Sure go for it @sawhitt !

**Comment by systemcatch** [comment]
#772 was a good try at implementing this functionality but it failed to account for any locales other than English. Future attempts at this should take into account that many languages don't separate with spaces (Chinese, Japanese) and don't always have a value followed by a unit (Swedish).

**Comment by svanita00** [comment]
Hi! I'm interested in working on this issue. I'll be taking a look at it for the next few weeks.

**Comment by anish-nya** [comment]
I am interested working on this issue.

**Comment by systemcatch** [comment]
Now that #956 has been merged I think we can close this.
