### ISSUE TITLE
Convert redundant blanks in dates automatically

### ISSUE THREAD

**Issue by WDBell** [arrow-py/arrow#421]
I want to answer this question using arrow: http://stackoverflow.com/questions/466345/converting-string-into-datetime.  With the first date, and an apparently suitable format I get,

```
>>> arrow.get('Jun 1 2005  1:33PM', 'MMM D YYYY H:mmA')
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python34\lib\site-packages\arrow\api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "C:\Python34\lib\site-packages\arrow\factory.py", line 198, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "C:\Python34\lib\site-packages\arrow\parser.py", line 159, in parse
    raise ParserError('Failed to match \'{0}\' when parsing \'{1}\''.format(final_fmt_pattern, string))
arrow.parser.ParserError: Failed to match '(?P<MMM>(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)) (?P<D>\d{1,2}) (?P<YYYY>\d{4}) (?P<H>\d{1,2}):(?P<mm>\d{2})(?P<A>(am|pm|PM|AM))' when parsing 'Jun 1 2005  1:33PM'
```

There are two blanks between 2005 and 1:33. If I remove the redundant blank I get, 

```
>>> arrow.get('Jun 1 2005 1:33PM', 'MMM D YYYY H:mmA')
<Arrow [2005-06-01T13:33:00+00:00]>
```

Am I missing a way of dealing with this circumstance or would you think it reasonable to consider altering the regex in get to allow redundant blanks?

**Comment by systemcatch** [comment]
There is a way to deal with this now that special characters can be escaped in the format string.

```shell
arrow.get('Jun 1 2005    1:33PM', 'MMM D YYYY[\s+]H:mmA')
<Arrow [2005-06-01T13:33:00+00:00]>
```
However that only only works if you know where the extra spaces will be. Do we want to do this automatically?

**Comment by jadchaar** [comment]
We can maybe add a flag to the `get()` method like `normalize_spaces` that would allow us to normalize all the spacing to a single one. E.g. we could turn `  Jun    1        2005    1:33PM` into `Jun 1 2005 1:33PM`. Is this what you'd like to be seen done automatically?

**Comment by systemcatch** [comment]
Yeah I think a flag could be a good option, I'm not really in favour of doing lots of hidden preprocessing based on what we think the user needs here.

**Comment by oakt** [comment]
Can we work on this?
