### ISSUE TITLE
Specify timezone with lat/long combo

### ISSUE THREAD

**Issue by espg** [arrow-py/arrow#427]
Hello,
Checking in to see how much interest there is for this as an enhancement. Basically, the idea is to add support for specifying a timezone by lat/long at creation-- so the following methods would yield equivalent results:

`local = utc.to('US/Pacific')`
`local = utc.to_geo(34.42, -119.69)`

...as would:

`arrow.now('US/Pacific')`
`arrow.now_geo('34.42, -119.69')`

Clearly, this could also be implemented as a flag within the `now` and `etc.to` methods instead of as separate functions if that conforms to the API better.
 
The way that this would work would be via lookup within a reference shapefile/database-- e.g. [this one](http://efele.net/maps/tz/world/ )

This wouldn't be terribly difficult to implement for present day, and I'd being willing to work on it if there is interest...but there would be a few caveats, at least for a first pass implementation:

1. Historical timezone support is a mess and would likely be very nontrivial to implement. For example, entering a timestamp in the 1950's with a lat/long pair would require checking to see both if the timezone definition had changed compared to the current polygon set, and if the daylight savings switchover was different. So a first pass on this would be most successful if historical geolocation of timezones was differed.

2. Nautical geolocation to time zone is also a bit messy. It could be oversimplified to occur at 15 degree increments (for international waters), or by defaulting to nearest valid timezone (national waters)... but delineating national waters can be tricky, especially in contested areas.

3. Ignoring the timezone polygon shifts from item 1 above, setting a time in the near future or recent past by lat/long pair would need a way of handling daylight savings time. This is probably doable if the lat/long combo includes the date stamp as well.

Despite the above sticky points, a basic method that allows creation of the timezone based on current time and lat/long pairs would probably meet the needs of most users... I think. Is this worth working on submitting a PR?

**Comment by czechben** [comment]
Is there any interest in implementing this enhancement?

Has anyone considered utilizing a Python package such as geonames and integrating this into the package requirements in order to make the lat/long translation easier?

**Comment by systemcatch** [comment]
I don't think we have a strong interest in building this into arrow, I'll close this issue for now but feel free to keep discussing the proposal.

**Comment by jadchaar** [comment]
This is an interesting proposal, but I feel like it would require an external dependency, which might be a tough sell to introduce into Arrow.
