### ISSUE TITLE
arrow.span_range doesn't start from the start_date that I requested

### ISSUE THREAD

**Issue by arLevi** [arrow-py/arrow#505]
I have the following code snippet

```
#!/usr/bin/python

import arrow

a = arrow.get("2017-12-13T00:00:00+00:00")
b = a.replace(weeks=+1)

# Doesn't work as expected
for span_start, span_end in arrow.Arrow.span_range('week', a, b):
    print "start:", span_start, "-", span_end

>>> start: 2017-12-11T00:00:00+00:00 - 2017-12-17T23:59:59.999999+00:00
>>> start: 2017-12-18T00:00:00+00:00 - 2017-12-24T23:59:59.999999+00:00

# Doesn't work as well
for dates in arrow.Arrow.interval('week', a, b, interval=1):
...

# Works as expected
for span_start in arrow.Arrow.range('week', a, b):
    print "start:", span_start

>>> start: 2017-12-13T00:00:00+00:00
>>> start: 2017-12-20T00:00:00+00:00
```

The issue here, is that `span_range` starts the span at `2017-12-11` instead of `2017-12-13` While `Arrow.range` gives the right result ( meaning; the date I requested to start from)

Basically, I can understand why `span_range` starts at `2017-12-11` - as it's Monday ( the beginning of the week) but I requested a span from a certain date & time - isn't Arrow suppose to consider my request ( Wednesday -> next Wednesday vs Monday -> next Monday ) ?

**Comment by systemcatch** [comment]
Hello @arLevi, sorry this took so long to get looked at.

I can see your point, it's kinda weird that span_range is stepping back to the start of the week. From https://github.com/crsmithdev/arrow/blob/master/arrow/arrow.py#L364 that seems to be intended though.

span_range uses span internally (https://github.com/crsmithdev/arrow/blob/master/arrow/arrow.py#L713) so the reason is probably in there.

**Comment by yiransii** [comment]
Hello, what is the status of this issue? do we want to make it such that span() always starts on Monday?

**Comment by areyal** [comment]
Hi, i don't think this is a bug, it is coherent with the 'span' behaviour. If it changes here, it should change in 'span' also.

**Comment by systemcatch** [comment]
Now that we have added the `exact` kwarg for `span_range`, `interval` this allows the behavior expected.

```shell
>>> a = arrow.get("2017-12-13T00:00:00+00:00")
>>> b=a.shift(weeks=+1)
>>> for span_start, span_end in arrow.Arrow.span_range('week', a, b, exact=True):
...     print("start:", span_start, "-", span_end)
... 
start: 2017-12-13T00:00:00+00:00 - 2017-12-19T23:59:59.999999+00:00
```

I'll close this now but feel free to make further comments.
