### ISSUE TITLE
Pandas Timestamp created from Arrow's don't behave correctly

### ISSUE THREAD

**Issue by antoine-gallix** [arrow-py/arrow#755]
I've encountered an issue while using Arrow to build panda's Timestamp data type. I've reported the bug on panda's repo but I've received an answer that suggest a solution might be on arrow's side so here I share the link to the issue: https://github.com/pandas-dev/pandas/issues/31793

What is your opinion on where should be the problem resolved? On Arrow's side to make it behave more like a datetime, or on Panda's side to reject or transform Arrow instances when used to create a Timestamp?

**Comment by jadchaar** [comment]
Hmm it seems to be because we use `dateutil` timezone objects, but Pandas uses `pytz`. Thoughts @systemcatch?

**Comment by systemcatch** [comment]
Hey @antoine-gallix thanks for the report.

Jad has hit the nail on the head here in that arrow uses `dateutil` everywhere for timezones. It looks like `pandas.Timestamp` supports dateutil tzinfo's already which is good. I'll jump onto the pandas issue and provide some thoughts in a bit.

**Comment by systemcatch** [comment]
https://github.com/pandas-dev/pandas/pull/37329 has been merged in to the pandas master branch. I believe this issue can be closed now.
