### ISSUE TITLE
Floats in humanize output for languages overriding _format_timeframe

### ISSUE THREAD

**Issue by krisfremen** [arrow-py/arrow#789]
## Issue Description

Doing humanize on languages that override _format_timeframe is spitting out floats instead of integers which is not nice on the eye.

```
arrow.utcnow().shift(weeks=5).humanize(locale="en", granularity="day")
'in 35 days'
arrow.utcnow().shift(weeks=5).humanize(locale="bg", granularity="day")
'напред 35.0 дни'
arrow.utcnow().shift(seconds=55000).humanize(locale="bg", granularity="minute")
'напред 916.6666666666666 минути'
```

## System Info

- 🖥 **OS name and version**: Debian Buster(10)
- 🐍 **Python version**: 3.7.3
- 🏹 **Arrow version**: 0.15.6

**Comment by mohtamba** [comment]
I would be interested in fixing this issue.

**Comment by krisfremen** [comment]
Hmm, I must've not pushed my fixes. I have two fixes, one of which breaks some tests due to ints vs floats.

Will push soon.

**Comment by egannon** [comment]
I can give this a try as well!
