### ISSUE TITLE
Add support for parsing natural language dates

### ISSUE THREAD

**Issue by ZeusFSX** [arrow-py/arrow#837]
## Feature Request

Can add some tokens in table **Supported Tokens**  for parsing the type of date: _"yesterday"_, _"today"_, _"month ago"_, etc?

**Comment by jadchaar** [comment]
This seems directly related to #360. We recently got a PR adding support for this (https://github.com/arrow-py/arrow/pull/772), but it did not account for locales and became inactive, so we decided to close it. If you would like to submit a PR for this, using https://github.com/arrow-py/arrow/pull/772 as a template, we would love to review it.
