### ISSUE TITLE
Implement remaining datetime methods

### ISSUE THREAD

**Issue by systemcatch** [arrow-py/arrow#840]
We need to implement `toordinal()` and `fromordinal()` along with the new `timestamp()` method.

Also our `isoformat()` method should be updated to include the `timespec` arg.

**Comment by pgogri** [comment]
Hi, I would like to work on this request and contribute to Arrow. Is this request still up for grabs?

**Comment by jadchaar** [comment]
It should be. Just keep in mind though that these methods are not supported on python <3.6, and our code base has not fully dropped support tor py27 and py35 just yet.

**Comment by pgogri** [comment]
I see, so the manner in which these methods interact with the rest of Arrow's codebase could be tricky. Is it important for these new methods to also work well with py27 and py35?

I wish to get a deeper understanding of the Arrow's codebase and its structure. Are there any suggestions or resources to help me do so?

**Comment by jadchaar** [comment]
Currently, we are supporting Python 2.7+, but we are planning to drop 2.7, 3.5 very soon. You can submit your PR with support for 3.6+, but it may take some time to get merged once we are fully committed to the deprecation.

**Comment by systemcatch** [comment]
@pgogri now that the big Python 2.7/3.5 PR has been merged I think you should be good to go here.

**Comment by pgogri** [comment]
Hi, I had a clarification, so I found that below is currently possible:

`>>> import arrow
>>> import datetime
>>> a = arrow.utcnow()
>>> a
<Arrow [2020-11-12T06:09:02.869023+00:00]>
>>> a_ord = a.toordinal()
>>> a_ord
737741`

I was just wondering whether this means that arrow can already support the toordinal() method of datetime?

For fromordinal() method, I think we need to build support so that it can return an arrow object with the command arrow.fromordinal()?

`>>> import arrow
>>> import datetime
>>> a = arrow.utcnow()
>>> a
<Arrow [2020-11-12T06:09:02.869023+00:00]>
>>> a_ord = a.toordinal()
>>> a_ord
737741
>>> arrow.fromordinal(a_ord)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'arrow' has no attribute 'fromordinal'
>>> datetime.datetime.fromordinal(a_ord)
datetime.datetime(2020, 11, 12, 0, 0)
>>> a.datetime.fromordinal(a_ord)
datetime.datetime(2020, 11, 12, 0, 0)
>>>`

Just looking for some clarification what are goals for the toordinal() and fromordinal() methods. Thanks.

**Comment by systemcatch** [comment]
Hey @pgogri no need to bother about the `timestamp()` stuff, we've already done that.

Seems like `toordinal()` works fine. For `fromordinal` we would normally integrate that with `arrow.get()` however this would conflict with unix timestamps. Let's do what you suggested.

```shell
>>> arrow.fromordinal(737741)
arrow.Arrow(2020, 11, 12, 0, 0 , 0)
```

@jadchaar any thoughts here?

**Comment by pgogri** [comment]
Hi @systemcatch , thanks for your reply,
Won't it be more like:
```
>>> arrow.fromordinal(737741)
<Arrow [2020-11-12T00:00:00+00:00]>

```
Or does that not work? Can you share a bit more on what you mean "when you say this (integrating with arrow.get()) would conflict with unix timestamps"?

**Comment by krisfremen** [comment]
> Or does that not work? Can you share a bit more on what you mean "when you say this (integrating with arrow.get()) would conflict with unix timestamps"?

Technically, 737741 is a valid unix timestamp, I believe @systemcatch was referring to the fact it would create ambiguity in parsing ordinals vs UNIX timestamps.

```
>>> datetime.fromtimestamp(737741)
datetime.datetime(1970, 1, 9, 7, 55, 41)
>>> datetime.fromordinal(737741)
datetime.datetime(2020, 11, 12, 0, 0)
```

**Comment by systemcatch** [comment]
@pgogri you are right I provided the new `__repr__`

**Comment by pgogri** [comment]
Thanks for all the clarifications! I have started to work on this, I will provide an update soon.

**Comment by jadchaar** [comment]
We should also make sure we support the `timespec` argument for `isoformat()`: https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat.

**Comment by pgogri** [comment]
Yes, am on it :)
