### ISSUE TITLE
humanize() rounding problem

### ISSUE THREAD

**Issue by mattiaverga** [arrow-py/arrow#848]
## Issue Description
Not sure if this is wanted or a bug. `humanize()` returns "a week ago" for deltas < 7 days.
For example:
```
>>> arrow.utcnow().shift(days=-6, hours=-9).humanize()
'6 days ago'
>>> arrow.utcnow().shift(days=-6, hours=-10).humanize()
'a week ago'
```
I would expect "a week ago" to be returned after 7 days have passed.

## System Info

- 🖥 **OS name and version**: Fedora 32
- 🐍 **Python version**: Python 3.8.5
- 🏹 **Arrow version**: arrow 0.16.0

**Comment by jadchaar** [comment]
It seems that the `humanize` function was originally designed with impreciseness in mind to give ballpark estimates for humanized date/time formats. That said, I think it would be nice to add an `exact` or `precise` keyword argument to allow users to choose which type of functionality they want, and we can adjust the bounds appropriately. What do you think @systemcatch ?
