### ISSUE TITLE
Use strptime tokens internally for parsing ISO 8601 week dates

### ISSUE THREAD

**Issue by systemcatch** [arrow-py/arrow#857]
Available once we drop Python 2.7

https://github.com/arrow-py/arrow/blob/master/arrow/parser.py#L414

**Comment by yiransii** [comment]
Hello, I am interested in working on this as well.

**Comment by systemcatch** [comment]
Hi @yiransii now that 2.7/3.5 are dropped this is doable, shall I assign you?

**Comment by yiransii** [comment]
@systemcatch yea sure

**Comment by yiransii** [comment]
@systemcatch hello, I am a bit confused with exactly where to use ```datetime.strptime()```. Could you please clarify? 

Under the function ```_build_datetime``` delcaration, there is a comment on line 420 about using ```strptime()```, which I think is for line 421 ```year, week = int(weekdate[0]), int(weekdate[1]) ```
However, I did some testing and it seems that ```weekdate``` is already a tuple: ```'weekdate': ('2011', '05', '4')```. So line 421 makes sense w/o using ```datetime.strptime()```. Am I misunderstanding something?

**Comment by systemcatch** [comment]
Hey @yiransii my idea is to do something similar to https://github.com/arrow-py/arrow/blob/master/arrow/parser.py#L464

That way there's no need for the `iso_to_gregorian` util function in the parser or https://github.com/arrow-py/arrow/blob/master/arrow/factory.py#L206

Does that make sense?

**Comment by yiransii** [comment]
@systemcatch 

Thank you so much for the clarification. 

I have updated ```parser.py``` and submitted a pull request. I have some dependency issues running tests locally but it has passed all tests as it shows in the pull request. 

Please review my pull request and let me know if anything is off. I can work on https://github.com/arrow-py/arrow/blob/master/arrow/factory.py#L206 as well.
