### ISSUE TITLE
Please support  time str or any params that arrow.get can sparse  to replace datetime expression in Arrow.range

### ISSUE THREAD

**Issue by CatNofishing** [arrow-py/arrow#867]
I notice that Arrow.range Arrow.span_range or other method  only can sparse Arrow or datetime object,  i thinks this is  unconvenient.  If  it can sparse any expressions that arrow.get can sparse, it  is will be good. 
![image](https://user-images.githubusercontent.com/33288114/95654808-219c5d80-0b35-11eb-82fe-397ea0c6f2b6.png)

Last, i think it is good to add all Arrow class method  api to arrow.api, It will be more simple and perfect.
For example arrow.range is better than arrow.Arrow.range

**Comment by systemcatch** [comment]
Hi @CatNofishing, we're not planning on changing the accepted inputs for `range` or `span_range`. I can take a look at changing some `arrow.Arrow.` imports to `arrow.`
