### ISSUE TITLE
MAX_TIMESTAMP throwing value error as of latest commit (windows10 + WSL2) [Possible bug in datetime]

### ISSUE THREAD

**Issue by pgogri** [arrow-py/arrow#880]
So, I was trying to run the test suite after working on my forked repo for a bit when I got this below message:

```
$ make test
rm -f .coverage coverage.xml
. venv/bin/activate; \
pytest
ImportError while loading conftest '/mnt/c/eecs481/HW6/arrow/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from arrow import arrow, factory, formatter, locales, parser
arrow/__init__.py:2: in <module>
    from .api import get, now, utcnow
arrow/api.py:8: in <module>
    from arrow.factory import ArrowFactory
arrow/factory.py:16: in <module>
    from arrow import parser
arrow/parser.py:8: in <module>
    from arrow.util import iso_to_gregorian, next_weekday, normalize_timestamp
arrow/util.py:5: in <module>
    from arrow.constants import MAX_TIMESTAMP, MAX_TIMESTAMP_MS, MAX_TIMESTAMP_US
arrow/constants.py:8: in <module>
    MAX_TIMESTAMP = (
E   ValueError: year 10000 is out of range
make: *** [Makefile:19: test] Error 4
```
Just to be sure, I cloned the original repo and it still gave the same error. After taking a closer look it looks like the MAX_TIMESTAMP initialization in the newest commit has problem:
```
MAX_TIMESTAMP = (
    datetime(3001, 1, 18, 23, 59, 59, 999999) if os.name == "nt" else datetime.max
).timestamp()
```
Especially the else branch - `datetime.max.timestamp()` is the issue. This problem has more to do with a possible bug in datetime library itself as below does not work:

```
>>> datetime.datetime.max
datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
>>> dmax = datetime.datetime.max
>>> dmax
datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
>>> dmax.timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year 10000 is out of range
```

After some snooping around I found that the largest value of datetime that does not crash on my OS (windows10 + WSL2) is datetime(9999, 12, 31, 18, 29, 59, 999999)
```
>>> dmax3 = datetime.datetime(9999, 12, 31, 18, 29, 59, 999999)
>>> dmax3.timestamp()
253402261200.0
>>> max_ts = dmax3.timestamp()
>>> max_date = datetime.datetime.fromtimestamp(max_ts)
>>> max_date
datetime.datetime(9999, 12, 31, 18, 30)
>>> dmax4 = datetime.datetime(9999, 12, 31, 19, 0, 0, 0)
>>> dmax4.timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year 10000 is out of range
```

This issue was not visible in the previous commit as in the previous version, the MAX_TIMESTAMP value was hardcoded to a working value as below:
![image](https://user-images.githubusercontent.com/71665911/99366061-1e3b8500-28de-11eb-97e8-dcd668729d78.png)

I think we should adjust the else branch to have a working value and datetime(9999, 12, 31, 18, 29, 59, 999999) works but is certainly not a maximum value. 

Any ideas how to deal with this?

**Comment by jadchaar** [comment]
Thanks for reporting this. Luckily this change has not yet made it to release, and was part of our recent Python2.7/3.5 deprecation PR. Just to clarify, this is occurring on a Windows-based system using WSL correct?

**Comment by pgogri** [comment]
Glad to help. Yes correct, I am on Windows 10 with WSL2.
