### ISSUE TITLE
Shift() doesn't work properly across dayling savings time changes

### ISSUE THREAD

**Issue by msarrel** [arrow-py/arrow#884]
## Issue Description

The `shift()` method does not work properly across daylight savings time changes.

When changing from standard time to daylight savings time, it skips an hour.  I would expect the following two for loops to produce the same results, but they do not.  The first is correct and the second is incorrect.

The first one does the shift in `UTC` and then converts to `US/Pacific`.  That produces the correct result.  The second does the shift in `US/Pacific` and then converts to `UTC`.  That produces the incorrect result.

```python
import arrow

t1 = arrow.get("2001-10-28T07:00:00", tzinfo="UTC")
print()
print("Fall Back Correct")
for h in range(26):
    print(h, t1.shift(hours=h).to("US/Pacific"), t1.shift(hours=h))

print()
print("Fall Back Incorrect")
t2 = arrow.get("2001-10-28T00:00:00", tzinfo="US/Pacific")
for h in range(26):
    print(h, t2.shift(hours=h), t2.shift(hours=h).to("utc"))
```

In the incorrect case, everything starting a two-hour shift or greater is incorrect.  You can see the gap in UTC in the right-hand column.

```
Fall Back Correct
0 2001-10-28T00:00:00-07:00 2001-10-28T07:00:00+00:00
1 2001-10-28T01:00:00-07:00 2001-10-28T08:00:00+00:00
2 2001-10-28T01:00:00-08:00 2001-10-28T09:00:00+00:00
3 2001-10-28T02:00:00-08:00 2001-10-28T10:00:00+00:00
4 2001-10-28T03:00:00-08:00 2001-10-28T11:00:00+00:00
5 2001-10-28T04:00:00-08:00 2001-10-28T12:00:00+00:00
6 2001-10-28T05:00:00-08:00 2001-10-28T13:00:00+00:00
7 2001-10-28T06:00:00-08:00 2001-10-28T14:00:00+00:00
8 2001-10-28T07:00:00-08:00 2001-10-28T15:00:00+00:00
9 2001-10-28T08:00:00-08:00 2001-10-28T16:00:00+00:00
10 2001-10-28T09:00:00-08:00 2001-10-28T17:00:00+00:00
11 2001-10-28T10:00:00-08:00 2001-10-28T18:00:00+00:00
12 2001-10-28T11:00:00-08:00 2001-10-28T19:00:00+00:00
13 2001-10-28T12:00:00-08:00 2001-10-28T20:00:00+00:00
14 2001-10-28T13:00:00-08:00 2001-10-28T21:00:00+00:00
15 2001-10-28T14:00:00-08:00 2001-10-28T22:00:00+00:00
16 2001-10-28T15:00:00-08:00 2001-10-28T23:00:00+00:00
17 2001-10-28T16:00:00-08:00 2001-10-29T00:00:00+00:00
18 2001-10-28T17:00:00-08:00 2001-10-29T01:00:00+00:00
19 2001-10-28T18:00:00-08:00 2001-10-29T02:00:00+00:00
20 2001-10-28T19:00:00-08:00 2001-10-29T03:00:00+00:00
21 2001-10-28T20:00:00-08:00 2001-10-29T04:00:00+00:00
22 2001-10-28T21:00:00-08:00 2001-10-29T05:00:00+00:00
23 2001-10-28T22:00:00-08:00 2001-10-29T06:00:00+00:00
24 2001-10-28T23:00:00-08:00 2001-10-29T07:00:00+00:00
25 2001-10-29T00:00:00-08:00 2001-10-29T08:00:00+00:00

Fall Back Incorrect
0 2001-10-28T00:00:00-07:00 2001-10-28T07:00:00+00:00
1 2001-10-28T01:00:00-07:00 2001-10-28T08:00:00+00:00
2 2001-10-28T02:00:00-08:00 2001-10-28T10:00:00+00:00
3 2001-10-28T03:00:00-08:00 2001-10-28T11:00:00+00:00
4 2001-10-28T04:00:00-08:00 2001-10-28T12:00:00+00:00
5 2001-10-28T05:00:00-08:00 2001-10-28T13:00:00+00:00
6 2001-10-28T06:00:00-08:00 2001-10-28T14:00:00+00:00
7 2001-10-28T07:00:00-08:00 2001-10-28T15:00:00+00:00
8 2001-10-28T08:00:00-08:00 2001-10-28T16:00:00+00:00
9 2001-10-28T09:00:00-08:00 2001-10-28T17:00:00+00:00
10 2001-10-28T10:00:00-08:00 2001-10-28T18:00:00+00:00
11 2001-10-28T11:00:00-08:00 2001-10-28T19:00:00+00:00
12 2001-10-28T12:00:00-08:00 2001-10-28T20:00:00+00:00
13 2001-10-28T13:00:00-08:00 2001-10-28T21:00:00+00:00
14 2001-10-28T14:00:00-08:00 2001-10-28T22:00:00+00:00
15 2001-10-28T15:00:00-08:00 2001-10-28T23:00:00+00:00
16 2001-10-28T16:00:00-08:00 2001-10-29T00:00:00+00:00
17 2001-10-28T17:00:00-08:00 2001-10-29T01:00:00+00:00
18 2001-10-28T18:00:00-08:00 2001-10-29T02:00:00+00:00
19 2001-10-28T19:00:00-08:00 2001-10-29T03:00:00+00:00
20 2001-10-28T20:00:00-08:00 2001-10-29T04:00:00+00:00
21 2001-10-28T21:00:00-08:00 2001-10-29T05:00:00+00:00
22 2001-10-28T22:00:00-08:00 2001-10-29T06:00:00+00:00
23 2001-10-28T23:00:00-08:00 2001-10-29T07:00:00+00:00
24 2001-10-29T00:00:00-08:00 2001-10-29T08:00:00+00:00
25 2001-10-29T01:00:00-08:00 2001-10-29T09:00:00+00:00
```
When changing from daylight savings time to standard time, it duplicates an hour.  I would expect the following two for loops to produce the same results, but they do not.  The first is correct and the second is incorrect.

The first one does the shift in `UTC` and then converts to `US/Pacific`.  That produces the correct result.  The second does the shift in `US/Pacific` and then converts to `UTC`.  That produces the incorrect result.

```python
import arrow

t3 = arrow.get("2001-04-01T08:00:00", tzinfo="UTC")
print()
print("Spring Forward Correct")
for h in range(24):
    print(h, t3.shift(hours=h).to("US/Pacific"), t3.shift(hours=h))

print()
print("Spring Forward Incorrect")
t4 = arrow.get("2001-04-01T00:00:00", tzinfo="US/Pacific")
for h in range(24):
    print(h, t4.shift(hours=h), t4.shift(hours=h).to("utc"))
```

In the incorrect case, everything starting a three-hour shift or greater is incorrect.  You can see the duplication in UTC in the right-hand column.

```
Spring Forward Correct
0 2001-04-01T00:00:00-08:00 2001-04-01T08:00:00+00:00
1 2001-04-01T01:00:00-08:00 2001-04-01T09:00:00+00:00
2 2001-04-01T03:00:00-07:00 2001-04-01T10:00:00+00:00
3 2001-04-01T04:00:00-07:00 2001-04-01T11:00:00+00:00
4 2001-04-01T05:00:00-07:00 2001-04-01T12:00:00+00:00
5 2001-04-01T06:00:00-07:00 2001-04-01T13:00:00+00:00
6 2001-04-01T07:00:00-07:00 2001-04-01T14:00:00+00:00
7 2001-04-01T08:00:00-07:00 2001-04-01T15:00:00+00:00
8 2001-04-01T09:00:00-07:00 2001-04-01T16:00:00+00:00
9 2001-04-01T10:00:00-07:00 2001-04-01T17:00:00+00:00
10 2001-04-01T11:00:00-07:00 2001-04-01T18:00:00+00:00
11 2001-04-01T12:00:00-07:00 2001-04-01T19:00:00+00:00
12 2001-04-01T13:00:00-07:00 2001-04-01T20:00:00+00:00
13 2001-04-01T14:00:00-07:00 2001-04-01T21:00:00+00:00
14 2001-04-01T15:00:00-07:00 2001-04-01T22:00:00+00:00
15 2001-04-01T16:00:00-07:00 2001-04-01T23:00:00+00:00
16 2001-04-01T17:00:00-07:00 2001-04-02T00:00:00+00:00
17 2001-04-01T18:00:00-07:00 2001-04-02T01:00:00+00:00
18 2001-04-01T19:00:00-07:00 2001-04-02T02:00:00+00:00
19 2001-04-01T20:00:00-07:00 2001-04-02T03:00:00+00:00
20 2001-04-01T21:00:00-07:00 2001-04-02T04:00:00+00:00
21 2001-04-01T22:00:00-07:00 2001-04-02T05:00:00+00:00
22 2001-04-01T23:00:00-07:00 2001-04-02T06:00:00+00:00
23 2001-04-02T00:00:00-07:00 2001-04-02T07:00:00+00:00

Spring Forward Incorrect
0 2001-04-01T00:00:00-08:00 2001-04-01T08:00:00+00:00
1 2001-04-01T01:00:00-08:00 2001-04-01T09:00:00+00:00
2 2001-04-01T03:00:00-07:00 2001-04-01T10:00:00+00:00
3 2001-04-01T03:00:00-07:00 2001-04-01T10:00:00+00:00
4 2001-04-01T04:00:00-07:00 2001-04-01T11:00:00+00:00
5 2001-04-01T05:00:00-07:00 2001-04-01T12:00:00+00:00
6 2001-04-01T06:00:00-07:00 2001-04-01T13:00:00+00:00
7 2001-04-01T07:00:00-07:00 2001-04-01T14:00:00+00:00
8 2001-04-01T08:00:00-07:00 2001-04-01T15:00:00+00:00
9 2001-04-01T09:00:00-07:00 2001-04-01T16:00:00+00:00
10 2001-04-01T10:00:00-07:00 2001-04-01T17:00:00+00:00
11 2001-04-01T11:00:00-07:00 2001-04-01T18:00:00+00:00
12 2001-04-01T12:00:00-07:00 2001-04-01T19:00:00+00:00
13 2001-04-01T13:00:00-07:00 2001-04-01T20:00:00+00:00
14 2001-04-01T14:00:00-07:00 2001-04-01T21:00:00+00:00
15 2001-04-01T15:00:00-07:00 2001-04-01T22:00:00+00:00
16 2001-04-01T16:00:00-07:00 2001-04-01T23:00:00+00:00
17 2001-04-01T17:00:00-07:00 2001-04-02T00:00:00+00:00
18 2001-04-01T18:00:00-07:00 2001-04-02T01:00:00+00:00
19 2001-04-01T19:00:00-07:00 2001-04-02T02:00:00+00:00
20 2001-04-01T20:00:00-07:00 2001-04-02T03:00:00+00:00
21 2001-04-01T21:00:00-07:00 2001-04-02T04:00:00+00:00
22 2001-04-01T22:00:00-07:00 2001-04-02T05:00:00+00:00
23 2001-04-01T23:00:00-07:00 2001-04-02T06:00:00+00:00
```
## System Info

- 🖥  **OS name and version**: macOS 10.14.6
- 🐍  **Python version**: Python 3.9.0
- 🏹  **Arrow version**: Arrow 0.17.0

**Comment by msarrel** [comment]
See https://github.com/arrow-py/arrow/issues/885

**Comment by msarrel** [comment]
See https://github.com/arrow-py/arrow/issues/871

**Comment by systemcatch** [comment]
Hi @msarrel, these results occur because the `UTC` timezone is never adjusted for dst, meaning no duplicates or gaps occur.

So the order of operations matters, starting in UTC then going to US/Pacific isn't the same as US/Pacific => UTC. All the examples shown look to be correct though I grant you the duplicate in the last one is weird but that tends to happen with datetimes that don't exist.

**Comment by msarrel** [comment]
Hi @systemcatch, I think we disagree on the nature of the issue.  I think there should never be duplicates or gaps, even when working in a time zone that uses daylight savings time.  I view this as a bug that needs to be fixed.  The same is true for my earlier issue https://github.com/arrow-py/arrow/issues/871.

In the Fall Back Incorrect case, it is incorrect to say that 2001-10-28T03:00:00-08:00 is three hours later than 2001-10-28T00:00:00-07:00.  It is four hours later.

Similarly, in the Spring Forward Incorrect case, it is incorrect to say that 2001-04-01T04:00:00-07:00 is four hours later than 2001-04-01T00:00:00-08:00.  It is three hours later.

And, I'm not the only one who has this same question.  Just today, someone else opened this issue https://github.com/arrow-py/arrow/issues/885.

**Comment by msarrel** [comment]
@systemcatch 
Just to add to the above, when calculating the difference between two times, you need to both take into account the different in the nominal hours and the UTC offsets.

In the Fall Back case, the correct difference is 4 h = (03 - 00) + ((-07) - (-08)).

In the Spring Forward case, the correct difference is 3 h = (04 - 00) + ((-08) - (-07)).

Although, as I do in my example, it's also possible to convert to UTC, do the operation and then convert back to US/Pacific.

**Comment by msarrel** [comment]
@systemcatch, Here's another way to think about it.  Look at this code:

```python
print()
print("Incorrect Fall Back")
t1 = arrow.get("2001-10-28T00:00:00", tzinfo="US/Pacific")
t2 = arrow.get("2001-10-28T03:00:00", tzinfo="US/Pacific")
print("t1:", t1)
print("t2:", t2)
print("t2 - t1:", t2 - t1)

print()
print("Correct Fall Back")
t3 = arrow.get("2001-10-28T00:00:00-07:00")
t4 = arrow.get("2001-10-28T03:00:00-08:00")
print("t3:", t3)
print("t4:", t4)
print("t4 - t3:", t4 - t3)

print()
print("Consistency")
print("t3 == t1:", t3 == t1)
print("t4 == t2:", t4 == t2)

print()
print("A Contradiction")
print("(t2 - t1) == (t4 - t3):", (t2 - t1) == (t4 - t3))
```

and it's output:

```
Incorrect Fall Back
t1: 2001-10-28T00:00:00-07:00
t2: 2001-10-28T03:00:00-08:00
t2 - t1: 3:00:00

Correct Fall Back
t3: 2001-10-28T00:00:00-07:00
t4: 2001-10-28T03:00:00-08:00
t4 - t3: 4:00:00

Consistency
t3 == t1: True
t4 == t2: True

A Contradiction
(t2 - t1) == (t4 - t3): False
```

We can see that the difference between t2 and t1 is incorrectly shown as 3 hours, while the difference between t4 and t3 is correctly shown as 4 hours.  Further, it seems that t3 is equal to t1 and t4 is equal to t2.  But, the difference between t2 and t1 is not equal to the difference between t4 and t3.  This is the contradiction at the center of the issue.  Just from a purely mathematical perspective, if t3 == t1 is true and t4 == t2 is true, then (t2 - t1) == (t4 - t3) must also be true.

**Comment by msarrel** [comment]
@systemcatch @areyal

Upon further investigation, it seems that the root cause of the bug (of this issue and of https://github.com/arrow-py/arrow/issues/871 and https://github.com/arrow-py/arrow/issues/885) is the Python `datetime` library.  Look at [PEP 431](https://www.python.org/dev/peps/pep-0431) and specifically the [Withdrawal section](https://www.python.org/dev/peps/pep-0431/#withdrawal).  I still find it very strange that the Python community would not fix this bug.  But, I can't hold you, the developer of Arrow, responsible for it.

[PEP 431](https://www.python.org/dev/peps/pep-0431) was superseded by [PEP 615](https://www.python.org/dev/peps/pep-0615/).  So, I was hopeful that the problem had finally been resolved.  But, sadly, that is not the case.

See this example code using `datetime` and `zoneinfo` that demonstrate the bug without the use of `arrow`.

```python
from datetime import datetime
from zoneinfo import ZoneInfo


print()
print("Incorrect Fall Back")
t1 = datetime(2001, 10, 28, 0, tzinfo=ZoneInfo("US/Pacific"))
t2 = datetime(2001, 10, 28, 3, tzinfo=ZoneInfo("US/Pacific"))
print("t1:", t1)
print("t2:", t2)
print("t2 - t1:", t2 - t1)

print()
print("Correct Fall Back")
# Notice the sign error here.
# I had to say GMT+7 to get GMT-7, and GMT+8 to get GMT-8.
t3 = datetime(2001, 10, 28, 0, tzinfo=ZoneInfo("Etc/GMT+7"))
t4 = datetime(2001, 10, 28, 3, tzinfo=ZoneInfo("Etc/GMT+8"))
print("t3:", t3)
print("t4:", t4)
print("t4 - t3:", t4 - t3)

print()
print("Consistency")
print("t3 == t1:", t3 == t1)
print("t4 == t2:", t4 == t2)

print()
print("A Contradiction")
print("(t2 - t1) == (t4 - t3):", (t2 - t1) == (t4 - t3))
```

and it's output:

```
Incorrect Fall Back
t1: 2001-10-28 00:00:00-07:00
t2: 2001-10-28 03:00:00-08:00
t2 - t1: 3:00:00

Correct Fall Back
t3: 2001-10-28 00:00:00-07:00
t4: 2001-10-28 03:00:00-08:00
t4 - t3: 4:00:00

Consistency
t3 == t1: True
t4 == t2: True

A Contradiction
(t2 - t1) == (t4 - t3): False
```

You can see that the result is the same as with the Arrow library above.

**Comment by systemcatch** [comment]
@msarrel as you said this behaviour originates in `datetime` itself. Posting in the datetime mailing list might provide you with a better explanation of why this way was chosen. The blog posts below are from the author of PEP 615 and contain lots of detail about python datetime semantics.

https://blog.ganssle.io/articles/2018/02/aware-datetime-arithmetic.html
https://blog.ganssle.io/articles/2018/02/a-curious-case-datetimes.html
