### ISSUE TITLE
range and span_range behave different if explicit tz is provided

### ISSUE THREAD

**Issue by areyal** [arrow-py/arrow#885]
The functions range and span_range behave different if explicit tz is provided, being tz the same of the provided start and end datetimes.
They provide an unexpected additional interval at the end of the range.

## Issue Description

Setup:
```
from arrow import Arrow
import pytz

tz = pytz.timezone("Europe/Madrid")

start = Arrow(2000,1,1,1).replace(tzinfo=tz)
end = Arrow(2000,2,1).replace(tzinfo=tz)
```

Test without explicit tz:
```

In [29]: result = list(Arrow.span_range('hour',start,end))

In [30]: len(result)
Out[30]: 745

In [31]: result[:2]
Out[31]:
[(<Arrow [2000-01-01T00:00:00+01:00]>,
  <Arrow [2000-01-01T00:59:59.999999+01:00]>),
 (<Arrow [2000-01-01T01:00:00+01:00]>,
  <Arrow [2000-01-01T01:59:59.999999+01:00]>)]

In [32]: result[-2:]
Out[32]:
[(<Arrow [2000-01-31T23:00:00+01:00]>,
  <Arrow [2000-01-31T23:59:59.999999+01:00]>),
 (<Arrow [2000-02-01T00:00:00+01:00]>,
  <Arrow [2000-02-01T00:59:59.999999+01:00]>)]

```

Test with explicit tz:
```

In [33]: result = list(Arrow.span_range('hour',start,end,tz=tz))

In [34]: len(result)
Out[34]: 746

In [35]: result[:2]
Out[35]:
[(<Arrow [2000-01-01T00:00:00+01:00]>,
  <Arrow [2000-01-01T00:59:59.999999+01:00]>),
 (<Arrow [2000-01-01T01:00:00+01:00]>,
  <Arrow [2000-01-01T01:59:59.999999+01:00]>)]

In [36]: result[-2:]
Out[36]:
[(<Arrow [2000-02-01T00:00:00+01:00]>,
  <Arrow [2000-02-01T00:59:59.999999+01:00]>),
 (<Arrow [2000-02-01T01:00:00+01:00]>,
  <Arrow [2000-02-01T01:59:59.999999+01:00]>)]


```

Test with naive datetimes and explicit tz

```
In [43]: start = Arrow(2000,1,1)

In [44]: end = Arrow(2000,2,1)

In [45]: result = list(Arrow.span_range('hour',start,end,tz=tz))

In [46]: len(result)
Out[46]: 746

In [47]: result[:2]
Out[47]:
[(<Arrow [2000-01-01T00:00:00+01:00]>,
  <Arrow [2000-01-01T00:59:59.999999+01:00]>),
 (<Arrow [2000-01-01T01:00:00+01:00]>,
  <Arrow [2000-01-01T01:59:59.999999+01:00]>)]

In [48]: result[-2:]
Out[48]:
[(<Arrow [2000-02-01T00:00:00+01:00]>,
  <Arrow [2000-02-01T00:59:59.999999+01:00]>),
 (<Arrow [2000-02-01T01:00:00+01:00]>,
  <Arrow [2000-02-01T01:59:59.999999+01:00]>)]

```

## System Info

- 🖥  **OS name and version**: Debian 10
- 🐍  **Python version**: 3.7.3
- 🏹  **Arrow version**: 0.17.0

**Comment by msarrel** [comment]
I opened a similar bug report last month.

https://github.com/arrow-py/arrow/issues/871

It also looks like shift() has a similar issue.

https://github.com/arrow-py/arrow/issues/884

**Comment by msarrel** [comment]
I've found a work-around.  Convert to UTC, do the range() or span_range() and then convert back to Europe/Madrid.

The above is not ideal, and I would prefer that they fix this bug.

**Comment by systemcatch** [comment]
Hey @areyal there's a couple of points to note here.

- pytz has a very different model for timezones compared to `python datetime`/`dateutil` (which we use internally), this can lead to unexpected results if you're not careful.
- `Arrow` objects are never naive.

```shell
>>> dt=Arrow(2000, 1, 1)
>>> dt
<Arrow [2000-01-01T00:00:00+00:00]>
>>> dt.tzinfo
tzutc()
```

I need to investigate your problem more thoroughly but thought the above points would be helpful.

**Comment by systemcatch** [comment]
Hey @areyal I can't replicate your results, can you show me your installed python packages with `pip list`?
