### ISSUE TITLE
Should arrow.get(None) work?

### ISSUE THREAD

**Issue by systemcatch** [arrow-py/arrow#900]
As per the title should the following work?

```shell
>>> arrow.get(None)
<Arrow [2020-12-20T20:12:12.631217+00:00]>
```

https://github.com/arrow-py/arrow/blob/master/arrow/factory.py#L169

There could be an issue where someone unintentionally passes `None` in but gets no error. Realistically is this used?

**Comment by nkitsaini** [comment]
Never had any issue with this. But it seems to be too implicit.

**Comment by systemcatch** [comment]
I think it's a potential gotcha but as you say I've never been caught by it myself.

**Comment by krisfremen** [comment]
I would agree toward it not working.

Everything that in theory isn't an actual string or object that can be parsed into an Arrow, should raise an exception at least.

**Comment by Armaxxx** [comment]
Can I help with this issue raising an exception?

**Comment by jadchaar** [comment]
Go for it @Armaxxx!
