### ISSUE TITLE
Cannot import arrow

### ISSUE THREAD

**Issue by Rich700000000000** [arrow-py/arrow#904]
## Issue Description

As part of another program, I installed arrow, and it seemed to proceed without errors:
```
Requirement already up-to-date: arrow in /root/.local/lib/python3.8/site-packages (0.17.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.0 in /usr/lib/python3/dist-packages (from arrow) (2.7.3)
```
Despite this, when I attempt to install it, I simply cannot.

```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'arrow'
>>> 
```

I am not using Anaconda, Docker, or any type of system abstraction. What could make a package simply not appear like this, and how would you suggest I resolve it?

## System Info

- 🖥  **Ubuntu 20.04 LTS**: 
- 🐍  **Python 3.8**: 
- 🏹  **Arrow version**: I cannot complete this test, as arrow will not appear.

**Comment by krisfremen** [comment]
Doesn't seem like a bug in arrow.

You seem to be installing the package locally as root.

Are you also running python interpreter as root? If you're running as another user, the packages of course, won't show up.

**Comment by nkitsaini** [comment]
Yeah not an arrow issue. @Rich700000000000  try running this 
```python
import sys
print(sys.path)
```
It'll help you see what are the locations where python is trying to find 'Arrow'

**Comment by Rich700000000000** [comment]
Here they are:

```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/local/lib/python3.8/dist-packages/snudown-1.1.5-py3.8-linux-x86_64.egg', '/usr/lib/python3/dist-packages']
>>> 
```

Should snudown be in there?

**Comment by krisfremen** [comment]
`/root/.local/lib/python3.8/site-packages` is where you're installing the package, yet this isn't in your PATH.

Install arrow as a regular user and not root. Or if you're running Python as root, and this is your path setup, then add that path to your PYTHONPATH.
