### ISSUE TITLE
Python versions mismatch in README

### ISSUE THREAD

**Issue by krisfremen** [arrow-py/arrow#908]
## Issue Description

![68747470733a2f2f696d672e736869656c64732e696f2f707970692f707976657273696f6e732f6172726f772e737667](https://user-images.githubusercontent.com/1108071/103392921-0f0b4200-4aee-11eb-802f-eb0f5bf29fee.png)

The badge coming from shields.io is displaying incorrect "Python versions supported".

**Comment by jadchaar** [comment]
This is correct @krisfremen. The current stable release v0.17.0 still supports Python 2.7 and 3.5, but when v1.0.0 is released very soon, it should show the correct versions. The current master branch is well ahead of the last tag for v0.17.0.

**Comment by krisfremen** [comment]
LOL, my bad. my wires must've gotten crossed

**Comment by jadchaar** [comment]
All good, v1.0 was supposed to ship back in October hah!
