### ISSUE TITLE
Docstring for Arrow.timestamp still shows the old syntax

### ISSUE THREAD

**Issue by ketiltrout** [arrow-py/arrow#946]
## Issue Description

The example in the docstring of `Arrow.timestamp` still shows the old syntax (property instead of method):
https://github.com/arrow-py/arrow/blob/cf8a0cc746c39cdc7109dbc91522429e82da3781/arrow/arrow.py#L852

I think this was missed in #929.

**Comment by systemcatch** [comment]
Thanks for spotting that, we'll correct it in the next release.
