### ISSUE TITLE
Azerbaijani Second Time Frame Issue

### ISSUE THREAD

**Issue by anishnya** [arrow-py/arrow#985]
Similar to the issue pointed out in #982, it appears in the Azerbaijani locale, the second time frame translates to "second" (saniyə) instead of "a second." I would assume looking at the rest of the time frame object within the locale, it should be "bir saniyə", but I would like to confirm with the community that this is in fact the correct translation.

**Comment by beucismis** [comment]
So is this true @anishnya ?
```python
>>> past = arrow.utcnow().shift(years=-1)
>>> past.humanize(locale="az")
'il əvvəl'
```

**Comment by anishnya** [comment]
@beucismis Yes that would work, but we are also looking for a more accurate translation of "a minute" in the AZ locale. I think the current translation is roughly equivalent to just "minute".

**Comment by sania-dsouza** [comment]
PR created for this: https://github.com/arrow-py/arrow/pull/1052
