### ISSUE TITLE
Improve Doc Strings in parser.py

### ISSUE THREAD

**Issue by anishnya** [arrow-py/arrow#988]
## Issue Description

I think we should improve the doc strings in parser.py to be more descriptive and similar like the rest of Arrow.

**Comment by izhun** [comment]
@anishnya Could you please concrete `the rest of Arrow`? What module or class can be used as reference?

**Comment by anishnya** [comment]
@izhun So for example arrow.py, we use the rest (see rest here for a more detailed explanation https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format) doc string format. We would like to see the doc strings in parser.py use the same format.

**Comment by krisfremen** [comment]
@anishnya hey, I've started on this, first pass, opened up a draft PR for now

**Comment by gh-adithya** [comment]
Hi! Is this issue still open? I would like to work on this issue as my first contribution for this project.

**Comment by krisfremen** [comment]
@gh-adithya yes, it's open.

I had https://github.com/arrow-py/arrow/pull/1010 as a draft PR a while back, you can continue off of that if you'd like.

**Comment by josefhoracek** [comment]
Is anyone working on this issue? I looked at the codebase and the #1010 draft PR, and I'd like to contribute.
