### ISSUE TITLE
"Dehumanize" is a terrible name for a function

### ISSUE THREAD

**Issue by barneygale** [arrow-py/arrow#999]
Arrow's `dehumanize()` parses an informal interval like 'a week ago' or 'in 2 months'.

I'm not sure of the best name for such a function, but "dehumanize" surely isn't it! In English this word has connotations far beyond the formality of expression, e.g. from wiktionary:

> To take away humanity; to remove or deny human qualities, characteristics, or attributes; to impersonalize.

It's usually employed when discussing some of the worst chapters of human history.

I'm not a big fan of `humanize()` either, but I'd suggest `robotize()` as an inverse.

**Comment by jadchaar** [comment]
Thanks for the report @barneygale. I agree that `dehumanize()` is not the best word to use for this function. We should probably make `reverse_humanize()` the primary inverse method name, but we'd most likely have to keep `dehumanize()` in the code base until a breaking release like v2.0. We can slate dehumanize for deprecation (with an appropriate warning message) if we decide to go through with the renaming.

**Comment by anishnya** [comment]
Yeah I'll be honest here, I didn't put an ounce of thought into naming the method dehumanize. I just kept the name proposed by the original issue and went with it. I have to agree with @jadchaar, we should probably wait until a major release like v2.0 to change it.

**Comment by systemcatch** [comment]
I think it's fine and works well as an inverse to humanize.

**Comment by jadchaar** [comment]
> Yeah I'll be honest here, I didn't put an ounce of thought into naming the method dehumanize. I just kept the name proposed by the original issue and went with it. I have to agree with @jadchaar, we should probably wait until a major release like v2.0 to change it.

What we can do is rename the current function to another name like `digitize()` or `roboticize()` or `reverse_humanize()` and make another function called dehumanize which just calls the renamed function and contains code raise a deprecation warning. That way we won't break compatibility with the current 1.x codebase, but we can make the more appropriate name the primary method.

**Comment by krisfremen** [comment]
I concur with @systemcatch and think the naming is fine as it is.

**Comment by emilian** [comment]
I am not a contributor, but have used arrow in my projects. Dehumanize is fine with me.

**Comment by barneygale** [comment]
I'm not sure if you guys are native english speakers, but 'dehumanize' is a word that already exists, has a widely-understood meaning, and has very little to do with the casualness of the language used. It's imprecise and therefore not good naming.

The arrow API already has a well-named function for applying an offset - `shift()`. Could add a new keyword argument like `string` or `casual`, `idiomatic` etc perhaps?

Arguably `d.humanize()` could be `str(d)`? (Wild speculation).

**Comment by jadchaar** [comment]
I’m in agreement with @barneygale in that we should change it just to prevent offending anyone going forward. It shouldn’t be too hard to do but we’d need to slate dehumanize for deprecation and alias it like I suggested. That would be the best happy medium for everyone :).

**Comment by emilian** [comment]
It is very clear to me what that function does based on the name. It is the inverse of humanize, so I don't know why you would consider it imprecise. Never had a problem with the name of the function.

**Comment by barneygale** [comment]
> It's the inverse of humanize

So I need to look up another function just to understand this one? Why not name the function something that conveys what it does without external reference?

**Comment by barneygale** [comment]
I agree it's probably offensive to some. For me the issue is its incongruousness and lack of precision more than its offensiveness.

**Comment by rtphokie** [comment]
Humanize is a great name, this is its opposite.

Is there a description of why this might be offensive, or a thought that it might offend someone?  If it's the former, let's discuss, if it's the latter, I question the value of putting effort in here.

I'm not seeing strong arguments above.

**Comment by barneygale** [comment]
https://en.wikipedia.org/wiki/Dehumanization 

It already means something, and it's nothing to do with parsing colloquially expressed dates.
